[tool.poetry]
name = "shuup-cms-blog"
version = "1.0.5"
description = "Shuup CMS Blog"
authors = ["Shuup <devs@shuup.com>"]


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
