# Generated by Django 2.2.15 on 2020-08-07 09:57

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_cms_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup_cms_blog.BlogArticle'),
        ),
    ]
